[parse]
[parse.html]
user-agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/144.0.0.0 Safari/537.36"

[[parse.html.allow]]
element = "article"
[[parse.html.allow]]
element = "main"

[[parse.html.skip]]
class = "c-pager"
[[parse.html.skip]]
class = "c-modal"
[[parse.html.skip]]
class = "c-announce-box"
[[parse.html.skip]]
class = "c-toast"
[[parse.html.skip]]
class = "c-ad"
[[parse.html.skip]]
class = "js-siori"
[[parse.html.skip]]
class = "p-reaction"
[[parse.html.skip]]
class = "p-novelpoint-form__body"
[[parse.html.skip]]
class = "l-foot-contents"
[[parse.html.skip]]
class = "remodal-wrapper"
