user-agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/144.0.0.0 Safari/537.36"

[[allow]]
element = "article"
[[allow]]
element = "main"

[[skip]]
class = "c-pager"
[[skip]]
class = "c-modal"
[[skip]]
class = "c-announce-box"
[[skip]]
class = "c-toast"
[[skip]]
class = "c-ad"
[[skip]]
class = "js-siori"
[[skip]]
class = "p-reaction"
[[skip]]
class = "p-novelpoint-form__body"
[[skip]]
class = "l-foot-contents"
[[skip]]
class = "remodal-wrapper"
